env:
  RUST_STABLE_VER: "1.91"
  RUST_MIN_VER: "1.79"
  CARGO_TERM_COLOR: always
  LD_LIBRARY_PATH: /usr/local/lib

name: CI

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  check:
    name: cargo check
    runs-on: ubuntu-latest
    container:
      image: docker.io/hdvanegasm/ajax:latest
    steps:
      - uses: actions/checkout@v4

      - name: download compiled libwrapper
        uses: actions/download-artifact@v5
        with:
          name: libwrapper
          path: thfhe/triples/build

      - name: install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_STABLE_VER }}

      - name: cargo check
        run: cargo check --all

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    container:
      image: docker.io/hdvanegasm/ajax:latest
    steps:
      - uses: actions/checkout@v4

      - name: install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_STABLE_VER }}
          components: rustfmt

      - name: cargo fmt
        run: cargo fmt --all

  test-stable:
    name: cargo test
    runs-on: ubuntu-latest
    container:
      image: docker.io/hdvanegasm/ajax:latest
    steps:
      - uses: actions/checkout@v4

      - name: download compiled libwrapper
        uses: actions/download-artifact@v5
        with:
          name: libwrapper
          path: thfhe/triples/build

      - name: install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_STABLE_VER }}

      - name: cargo test
        run: cargo test --all

  doc:
    name: cargo doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: cargo test doc
        run: cargo test --doc --workspace --all-features

      - name: cargo doc
        run: cargo doc --workspace --no-default-features --no-deps --document-private-items